### ISSUE TITLE
Skill: (1) Use the `simple_form` gem to simplify forms in Rails

### ISSUE THREAD

**Issue by snurby7** [snurby7/tc359_rails_final#2]
Should be implemented on every form that I found, looks much better

Calling @chrisvfritz

**Comment by chrisvfritz** [comment]
I agree! Very clean. :smiley: Just a couple items of note:

- Out of curiosity, why did [you set `:required` to false here](https://github.com/snurby7/tc359_rails_final/blob/master/app/views/sessions/new.html.erb)? Aren't both of those fields required?
- In general, I'll only set a label *or* a placeholder if they'd have the same value. Everything looks great on the review form, but for the sessions form, I would ditch either the labels or the placeholders.

**Comment by snurby7** [comment]
Not sure what I was thinking on the first one. I agree on the second one as well, seemed a bit redundant, just got into the form filling mentality. Should be fixed though.

**Comment by chrisvfritz** [comment]
:+1: Looks good!
